import config from '../config.js'

// Meta Instagram Graph API client — real publishing, no dry-run/fake success path.
// Requires a real Instagram Business Account linked to a Facebook Page, plus a
// long-lived access token (stored per seller+category in the instagram_accounts table).
// None of these credentials can be generated by this codebase — they must come from
// the seller's own Meta Business Suite / developer app.

const GRAPH_VERSION = config.instagram?.graphApiVersion || 'v21.0'
const GRAPH_BASE = `https://graph.facebook.com/${GRAPH_VERSION}`

async function graphRequest(path, { method = 'GET', params = {}, accessToken } = {}) {
  if (!accessToken) {
    throw new Error('Instagram access token missing — connect an Instagram Business Account for this category first.')
  }

  const url = new URL(`${GRAPH_BASE}${path}`)
  const searchParams = method === 'GET' ? url.searchParams : new URLSearchParams()
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null) searchParams.set(key, value)
  }
  searchParams.set('access_token', accessToken)
  if (method === 'GET') {
    url.search = searchParams.toString()
  }

  const response = await fetch(url, {
    method,
    ...(method !== 'GET' ? {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: searchParams.toString()
    } : {})
  })

  const body = await response.json().catch(() => null)
  if (!response.ok) {
    const message = body?.error?.message || `Graph API request failed with status ${response.status}`
    const err = new Error(message)
    err.graphError = body?.error
    err.status = response.status
    throw err
  }
  return body
}

// Step 1: create a media container for a single image post
export async function createMediaContainer({ igBusinessAccountId, accessToken, imageUrl, caption }) {
  if (!imageUrl) throw new Error('imageUrl is required to create an Instagram media container')
  return graphRequest(`/${igBusinessAccountId}/media`, {
    method: 'POST',
    accessToken,
    params: { image_url: imageUrl, caption: caption || '' }
  })
}

// Step 2: publish a previously created container
export async function publishContainer({ igBusinessAccountId, accessToken, creationId }) {
  if (!creationId) throw new Error('creationId is required to publish an Instagram media container')
  return graphRequest(`/${igBusinessAccountId}/media_publish`, {
    method: 'POST',
    accessToken,
    params: { creation_id: creationId }
  })
}

// Convenience: create + publish in one call
export async function publishImagePost({ igBusinessAccountId, accessToken, imageUrl, caption }) {
  const container = await createMediaContainer({ igBusinessAccountId, accessToken, imageUrl, caption })
  const published = await publishContainer({ igBusinessAccountId, accessToken, creationId: container.id })
  return { creationId: container.id, mediaId: published.id }
}

// Exchange a short-lived token (from the OAuth login flow) for a long-lived one (~60 days)
export async function exchangeForLongLivedToken({ shortLivedToken }) {
  const { appId, appSecret } = config.instagram || {}
  if (!appId || !appSecret) {
    throw new Error('META_APP_ID / META_APP_SECRET must be set to exchange tokens')
  }
  const url = new URL(`${GRAPH_BASE}/oauth/access_token`)
  url.searchParams.set('grant_type', 'fb_exchange_token')
  url.searchParams.set('client_id', appId)
  url.searchParams.set('client_secret', appSecret)
  url.searchParams.set('fb_exchange_token', shortLivedToken)

  const response = await fetch(url)
  const body = await response.json().catch(() => null)
  if (!response.ok) {
    throw new Error(body?.error?.message || 'Failed to exchange Instagram token')
  }
  return body // { access_token, token_type, expires_in }
}

// Refresh an already-long-lived token before it expires
export async function refreshLongLivedToken({ accessToken }) {
  return graphRequest('/oauth/access_token', {
    accessToken,
    params: { grant_type: 'ig_refresh_token' }
  })
}
